export type RegisteredCollectionFacility = {
  registryCode: string;
  name: string;
  district: string;
  locality: string;
};

export const COLLECTION_FACILITY_SOURCE_URL =
  'https://hrm.dghs.gov.bd/public/facility-registry/reports/organization-list';

// Curated from the supplied DGHS facility export on 2026-07-30. Only rows whose
// official facility Type is "Blood Bank" are suggested. A registry category is
// not proof that a service is currently operating, so requesters must confirm
// collection and transfusion arrangements directly with the facility.
const REGISTERED_BLOOD_BANK_ROWS = [
  ["10022186", "BOGURA ROKTO PORISONCHALON KENDRO (BLOOD BANK)", "Bogura", "Bogura Sadar"],
  ["10031049", "Component Blood Transfusion & Service Center", "Bogura", "Bogura Sadar"],
  ["10028247", "NEW BOGURA BLOOD BANK", "Bogura", "Bogura Sadar"],
  ["10028133", "TMSS Medical College & Rafatullah Community Hospital", "Bogura", "Bogura Sadar"],
  ["10033521", "UTTARA BLOOD BANK & TRANSFUSION CENTER", "Bogura", "Bogura Sadar"],
  ["10036120", "Uposhom blood bank brahmanbaria", "Brahmanbaria", "Brahmanbaria Sadar"],
  ["10033738", "Chapai Blood Bank And Transfusion Centre", "Chapainawabganj", "Chapainawabganj Sadar"],
  ["10038898", "Alif Hospital Diagnostic Center & blood bank  Transfusion Centre", "Chattogram", "Hathazari"],
  ["10034650", "Chattagram International Medical College & Hospital (CIMCH)", "Chattogram", "Chandgaon"],
  ["10025822", "Chattogram Maa-Shishu O General Hospital", "Chattogram", "Double Mooring"],
  ["10027682", "CHITTAGONG BLOOD BANK & TRANSFUSION CENTER.", "Chattogram", "Panchlaish"],
  ["10031174", "EVERCARE HOSPITAL CHATTOGRAM", "Chattogram", "Hathazari"],
  ["10038891", "Evergreen Blood Bank & Hematology Center", "Chattogram", "Panchlaish"],
  ["10038904", "Fatikchhari blood bank & transfusion center", "Chattogram", "Fatikchari"],
  ["10026953", "Imperial Hospital Limited", "Chattogram", "Pahartali"],
  ["10029055", "Jiban Blood Bank And Transfusion Medicine Centre", "Chattogram", "Satkania"],
  ["10028249", "Karnafuli Blood Bank and Thalassemia Center", "Chattogram", "Panchlaish"],
  ["10028148", "Landsteiner Blood Bank & Transfusion Medicine Centre", "Chattogram", "Panchlaish"],
  ["10026820", "LIFE SAVE BLOOD BANK & TRANSFUSION CENTRE", "Chattogram", "Panchlaish"],
  ["10033510", "M/S Hoque and Hadi  Memorial Blood Bank, Surgiscope Hospital (Pvt)Ltd. Unit-2", "Chattogram", "Panchlaish"],
  ["10030532", "Modern Blood Bank & Transfusion Centre", "Chattogram", "Panchlaish"],
  ["10033514", "PARKVIEW HOSPITAL LTD.", "Chattogram", "Panchlaish"],
  ["10030940", "Sandwip Medical Centre Blood Bank", "Chattogram", "Sandwip"],
  ["10038902", "SHAJINAZ HOSPITAL LIMITED", "Chattogram", "Bayejid Bostami"],
  ["10033447", "UNIQUE BLOOD BANK & TRANSFUSION CENTRE", "Chattogram", "Hathazari"],
  ["10025833", "Accura Blood Bank & Transfusion Centre", "Cox's Bazar", "Cox's Bazar Sadar"],
  ["10036081", "City Blood Bank and Transfusion Medicine Center", "Cumilla", "Cumilla Adarsha Sadar"],
  ["10021756", "Eastern Medical College Hospital", "Cumilla", "Burichang"],
  ["10033356", "MAINAMOTI MEDICAL COLLEGE & HOSPITAL", "Cumilla", "Cumilla Adarsha Sadar"],
  ["10038909", "NATIONAL BLOOD BANK & TRANSFUSION CENTRE", "Cumilla", "Cumilla Adarsha Sadar"],
  ["10026825", "NEW SAVE LIFE BLOOD BANK & DIAGNOSTIC CENTER", "Cumilla", "Cumilla Adarsha Sadar"],
  ["10034889", "Active Blood Bank, Transfusion And Diagnostic Center", "Dhaka", "Chak Bazar"],
  ["10022073", "Ad-din Barrister Rafique-ul-Huq Hospital", "Dhaka", "Shyampur"],
  ["10028888", "Ad-din womens medical college hospital", "Dhaka", "Shahbag"],
  ["10030831", "AHSANIA MISSION CANCER & GENERAL HOSPITAL", "Dhaka", "Uttara  Paschim"],
  ["10030217", "Ahsania Mission Cancer and General Hospital", "Dhaka", "Kafrul"],
  ["10027361", "Aichi Medical College & Hospital Ltd.", "Dhaka", "Demra"],
  ["10038901", "Akota Blood Bank And Transfusion Center", "Dhaka", "Kotwali"],
  ["10025818", "Al-Helal  Specialized Hospital Limited (Blood Bank)", "Dhaka", "Kafrul"],
  ["10030786", "Al-Manar Hospital Ltd.", "Dhaka", "Mohammadpur"],
  ["10021856", "Alif Blood Bank And Transfusion Centre", "Dhaka", "Dhanmondi"],
  ["10022668", "AMZ Hospital Ltd.", "Dhaka", "Badda"],
  ["10031177", "Anwer Khan Modern Blood Bank And Transfusion Centre", "Dhaka", "Kalabagan"],
  ["10021422", "ASGAR ALI HOSPITAL", "Dhaka", "Gendaria"],
  ["10025816", "Ashiyan Medical College Hospital", "Dhaka", "Khilkhet"],
  ["10027923", "AUTHENTIC  HOSPITAL", "Dhaka", "Chak Bazar"],
  ["10025815", "Bandhan Blood Bank and Transfusion Center", "Dhaka", "Chak Bazar"],
  ["10030042", "Bangladesh Blood Bank and Transfusion Center", "Dhaka", "Mohammadpur"],
  ["10029726", "Bangladesh Institute Of Health Sciences (BIHS) General Hospital", "Dhaka", "Mirpur"],
  ["10031455", "Bangladesh Medical College Hospital", "Dhaka", "Mohammadpur"],
  ["10025821", "Bangladesh Specialized Hospital Ltd. (BSHL)", "Dhaka", "Adabor"],
  ["10026287", "BANGLADESH SPINE & ORTHOPAEDIC GENERAL HOSPITAL (PVT.) LTD.", "Dhaka", "Mirpur"],
  ["10026288", "Bangladesh Thalassaemia Hospital", "Dhaka", "Kalabagan"],
  ["10027826", "Bashundhara Ad-din Medical College Hospital", "Dhaka", "Keraniganj"],
  ["10031292", "BAVS Metarnity Blood Transfusion Center", "Dhaka", "Mirpur"],
  ["10033999", "Better Life Hospital Ltd.", "Dhaka", "Rampura"],
  ["10025820", "BIRDEM General Hospital", "Dhaka", "Shahbag"],
  ["10032173", "Blood Bank of Filaria and General Hospital", "Dhaka", "Savar"],
  ["10027939", "BLOOD ZONE TRANSFUSION MEDICINE & DAY CARECENTRE", "Dhaka", "Banani"],
  ["10025823", "BRB Hospitals Limited", "Dhaka", "Sher-e-bangla Nagar"],
  ["10033511", "CENTER FOR KIDNEY DISEASES & UROLOGY HOSPITAL", "Dhaka", "Sher-e-bangla Nagar"],
  ["10025824", "Central  Hospital Ltd", "Dhaka", "Dhanmondi"],
  ["10031874", "City Hospital Ltd.", "Dhaka", "Mohammadpur"],
  ["10030490", "CREATIVE BLOOD BANK AND TRANSFUSION CENTER", "Dhaka", "Chak Bazar"],
  ["10033518", "Delta Health Care, Jatrabari Ltd.", "Dhaka", "Shyampur"],
  ["10030178", "Delta Health Care, Mirpur Ltd", "Dhaka", "Pallabi"],
  ["10028891", "Delta Hospital Limited", "Dhaka", "Mirpur"],
  ["10027374", "Dhaka central International medical college & Hospital", "Dhaka", "Adabor"],
  ["10027990", "DHAKA COMMUNITY MEDICAL COLLEGE HOSPITAL BLOOD BANK", "Dhaka", "Kotwali"],
  ["10030625", "DMFR Molecular Lab and Diagnostics BD Limited", "Dhaka", "Sher-e-bangla Nagar"],
  ["10033811", "Doctors Blood Bank & Transfusion Center", "Dhaka", "Dhanmondi"],
  ["10031032", "Dr. Azmal Hospital Ltd.", "Dhaka", "Mirpur"],
  ["10033608", "Dr. Sirajul Islam Medical College & Hospital Ltd", "Dhaka", "Khilgaon"],
  ["10031204", "EAST-WEST MEDICAL COLLEGE & HOSPITAL LIMITED", "Dhaka", "Turag"],
  ["10027307", "Enam Medical Hospital (Pvt.) Ltd.", "Dhaka", "Savar"],
  ["10029007", "Evercare Hospital Dhaka", "Dhaka", "Bhatara"],
  ["10029376", "EXIM Bank Hospital", "Dhaka", "Kafrul"],
  ["10033520", "Famous Blood Bank", "Dhaka", "Mohammadpur"],
  ["10038894", "Farabi General Hospital Limited", "Dhaka", "Kalabagan"],
  ["10036747", "Gonoshasthaya blood bank", "Dhaka", "Savar"],
  ["10026241", "Gonoshasthaya Blood Bank & Transfusion Center", "Dhaka", "New Market"],
  ["10038910", "GRACE HOSPITAL", "Dhaka", "Dhanmondi"],
  ["10031906", "Green Life Hospital Ltd", "Dhaka", "Kalabagan"],
  ["10027638", "Green View Clinic Blood Bank", "Dhaka", "Kalabagan"],
  ["10028973", "HEALTH AND HOPE LTD", "Dhaka", "Kalabagan"],
  ["10030240", "Hi-Care General Hospital Ltd.", "Dhaka", "Uttara  Paschim"],
  ["10021784", "Hitech Multicare Hospital Ltd", "Dhaka", "Kafrul"],
  ["10029082", "IBN SINA HOSPITAL", "Dhaka", "Mohammadpur"],
  ["10034130", "Ibn Sina Medical College Hospital", "Dhaka", "Mirpur"],
  ["10028464", "Ibrahim Cardiac Hospital & Research Institute", "Dhaka", "Shahbag"],
  ["10028260", "Insaf Barakah Kidney and General Hospital", "Dhaka", "Tejgaon"],
  ["10035542", "ISLAMI BANK CENTRAL HOSPITAL", "Dhaka", "Paltan"],
  ["10038893", "ISLAMI BANK HOSPITAL AND CARDIAC CENTRE MIRPUR", "Dhaka", "Pallabi"],
  ["10030695", "ISLAMI BANK HOSPITAL MIRPUR", "Dhaka", "Pallabi"],
  ["10033473", "Islami Bank Hospital Motijheel", "Dhaka", "Motijheel"],
  ["10022018", "Islami Bank Hospital, Mugda", "Dhaka", "Mugda Para"],
  ["10021653", "ISLAMI BANK SPECIALISED  GENERAL HOSPITAL NAYAPALTAN", "Dhaka", "Paltan"],
  ["10022136", "Khidmah Hospital (Pvt) Ltd.", "Dhaka", "Khilgaon"],
  ["10026463", "Kidney Foundation", "Dhaka", "Mirpur"],
  ["10033658", "Kingston Blood Bank", "Dhaka", "Mirpur"],
  ["10031774", "LAB ONE BLOOD BANK", "Dhaka", "Uttara  Paschim"],
  ["10033517", "Labaid Blood Bank", "Dhaka", "Dhanmondi"],
  ["10038911", "Labaid Cancer Hospital & Super Speciality Centre Ltd.", "Dhaka", "Dhanmondi"],
  ["10038896", "Life Care Blood Bank and Transfusion Centre.", "Dhaka", "Rampura"],
  ["10022191", "Lions  Blood Bank", "Dhaka", "Sher-e-bangla Nagar"],
  ["10027481", "Lubana General Hospital (Pvt.) Ltd.", "Dhaka", "Uttara  Paschim"],
  ["10028648", "MALIHA BLOOD BANK & TRANSFUSION CENTER", "Dhaka", "Mohammadpur"],
  ["10034790", "Marine Health Care Pvt. Ltd.", "Dhaka", "Khilkhet"],
  ["10033549", "Medical College for Women & Hospital", "Dhaka", "Uttara  Paschim"],
  ["10030980", "Metropolitan Medical Centre Ltd.", "Dhaka", "Tejgaon Ind. Area"],
  ["10034302", "MILLENNIUM SPECIALIZED HOSPITAL LTD.", "Dhaka", "Sutrapur"],
  ["10035135", "Monowara Hospital (Pvt) Ltd.", "Dhaka", "Paltan"],
  ["10028176", "MONOWARA ORTHOPAEDIC AND GENERAL HOSPITAL", "Dhaka", "Jatrabari"],
  ["10027088", "Mukti Blood Bank And Transfusion Center", "Dhaka", "Dhanmondi"],
  ["10034301", "National Heart Foundation Hospital and Research Institute", "Dhaka", "Mirpur"],
  ["10028732", "New Bangladesh Blood Bank", "Dhaka", "Kalabagan"],
  ["10026901", "Nirapad Blood Bank & Transfusion Center", "Dhaka", "Kalabagan"],
  ["10033527", "Northern International Medical College Hospital", "Dhaka", "Dhanmondi"],
  ["10028609", "ORYX BIO-TECH LTD", "Dhaka", "Sher-e-bangla Nagar"],
  ["10038913", "Peoples Care Hospital", "Dhaka", "Gulshan"],
  ["10033522", "Popular Medical College Hospital (Blood Bank)", "Dhaka", "New Market"],
  ["10036119", "Radium Blood Bank & Transfusion Center", "Dhaka", "Mohammadpur"],
  ["10031195", "RAJDHANI BLOOD BANK & TRANSFUSION CENTER", "Dhaka", "Mohammadpur"],
  ["10033680", "Rushmono  Poly  Clinic  (PVT)  LTD.", "Dhaka", "Shahbag"],
  ["10021490", "SAJIDA HOSPITAL", "Dhaka", "Keraniganj"],
  ["10038897", "Salauddin Specialized Hospital Ltd.", "Dhaka", "Wari"],
  ["10034792", "SAVAR PRIME HOSPITAL", "Dhaka", "Savar"],
  ["10038912", "Seba Blood Bank And Transfusion Center", "Dhaka", "Mugda Para"],
  ["10026392", "SENIOR CITIZEN HEALTHCARE LTD.", "Dhaka", "Bhatara"],
  ["10035008", "Shadhin Blood Bank And Transfusion Center", "Dhaka", "Bangshal"],
  ["10027555", "Shahabuddin Medical College Hospital", "Dhaka", "Gulshan"],
  ["10033516", "Shaheed Monsur Ali Medical College Hospital", "Dhaka", "Uttara  Paschim"],
  ["10031935", "Ship International  hospital.", "Dhaka", "Turag"],
  ["10027589", "SQUARE HOSPITALS  LIMITED (Blood Bank)", "Dhaka", "Sher-e-bangla Nagar"],
  ["10038905", "Thalassemia Blood Bank", "Dhaka", "Shajahanpur"],
  ["10033623", "The Barakah General Hospital Ltd.", "Dhaka", "Motijheel"],
  ["10033513", "The Diagnosis & Pathology Center", "Dhaka", "Kalabagan"],
  ["10031107", "THE MARKS ENT CLINIC & GENERAL HOSPITAL (PVT) LTD", "Dhaka", "Mirpur"],
  ["10025847", "TRAUMA CENTER & AO ORTHOPAEDIC HOSPITAL (PVT.) LIMITED", "Dhaka", "Mohammadpur"],
  ["10038916", "UNICO HOSPITALS PLC (Blood Bank)", "Dhaka", "Dhanmondi"],
  ["10038900", "UNIQUE BLOOD BANK & TRANSFUSION  CENTER", "Dhaka", "Banani"],
  ["10038915", "UNITED HEALTHCARE SERVICES LTD", "Dhaka", "Badda"],
  ["10031305", "United Hospital Limited", "Dhaka", "Gulshan"],
  ["10029800", "Universal Medical College & Hospital", "Dhaka", "Tejgaon"],
  ["10030712", "Uttara Adhunik Medical College Hospital", "Dhaka", "Uttara  Paschim"],
  ["10034843", "Uttara Blood Bank & Transfusion Center", "Dhaka", "Uttara  Paschim"],
  ["10033902", "UTTARA CRESCENT CLINIC (PVT.) LIMITED.", "Dhaka", "Uttara  Paschim"],
  ["10027856", "VOLUNTARY BLOOD DONATION PROGRAM (Quantum Faundation)", "Dhaka", "Paltan"],
  ["10030809", "Zainul Haque Sikder Womens Medical College & Hospital", "Dhaka", "Dhanmondi"],
  ["10038908", "Jagoron Blood Bank And  Transfusion Center", "Dinajpur", "Birganj"],
  ["10027776", "LAMB Hospital", "Dinajpur", "Parbatipur"],
  ["10027117", "MEDINET TRUST BLOOD BANK", "Dinajpur", "Dinajpur Sadar"],
  ["10033519", "City Medical College & Hospital", "Gazipur", "Gazipur Sadar"],
  ["10033509", "International Medical College Hospital", "Gazipur", "Gazipur Sadar"],
  ["10033515", "KPJ Specialized Hospital & Nursing College", "Gazipur", "Gazipur Sadar"],
  ["10038895", "M A RASHID HOSPITAL (PVT) LTD.", "Jamalpur", "Jamalpur Sadar"],
  ["10032108", "(BLOOD BANK) KHULNA CITY MEDICAL COLLEGE HOSPITAL", "Khulna", "Khulna Sadar"],
  ["10029150", "Akij Medical College Hospital", "Khulna", "Khulna Sadar"],
  ["10038888", "JAHURUL ISLAM MEDICAL COLLEGE & HOSPITAL", "Kishoreganj", "Bajitpur"],
  ["10038890", "KUSHTIA BLOOD BANK & TRANSFUSION CENTRE", "Kushtia", "Kushtia Sadar"],
  ["10038887", "Manikganj Sandhani Diagnostic & Blood Bank", "Manikganj", "Manikganj Sadar"],
  ["10031360", "Monno Medical College  Hospital", "Manikganj", "Manikganj Sadar"],
  ["10028754", "Community Based Medical College Hospital Blood Transfusion Center", "Mymensingh", "Mymensingh Sadar"],
  ["10029648", "Nirapad Blood Transfussion Service Center", "Mymensingh", "Mymensingh Sadar"],
  ["10034541", "HEALTH RESORT  HOSPITAL", "Narayanganj", "Narayanganj Sadar"],
  ["10026805", "MOHANAGAR BLOOD BANK & TRANSFUSION CENTER", "Narayanganj", "Narayanganj Sadar"],
  ["10030447", "Pro-Active Medical College & Hospital Limited", "Narayanganj", "Narayanganj Sadar"],
  ["10034906", "The Barakah Hospital Madonpur Ltd.", "Narayanganj", "Bandar"],
  ["10033771", "US-Bangla Medical College & Hospital", "Narayanganj", "Rupganj"],
  ["10021812", "Chalon Bil Nirapod Blood Parisanchalon Centre", "Natore", "Natore Sadar"],
  ["10033512", "NATORE BLOOD BANK", "Natore", "Natore Sadar"],
  ["10038903", "United Blood Bank", "Natore", "Natore Sadar"],
  ["10033523", "Noakhali Blood Bank & Transfusion Center", "Noakhali", "Noakhali Sadar"],
  ["10038889", "Pabna Blood Bank and Transfusion Centre", "Pabna", "Pabna Sadar"],
  ["10038907", "Uthshargo Foundation Blood Bank Pabna", "Pabna", "Pabna Sadar"],
  ["10038906", "ADARSHA DEAGNOSTIC CENTER & BLOOD BANK", "Panchagarh", "Panchagarh Sadar"],
  ["10027971", "Sabina Memorial Blood Bank", "Panchagarh", "Panchagarh Sadar"],
  ["10034617", "Islami Bank Medical College Hospital Blood Bank, Rajshahi", "Rajshahi", "Shah Makhdum"],
  ["10028794", "New Safe Blood Bank", "Rajshahi", "Boalia"],
  ["10034606", "RAJSHAHI BLOOD BANK AND TRANSFUSION CENTRE, RAJSHAHI.", "Rajshahi", "Rajpara"],
  ["10038899", "Shah Makhdum Blood Bank & Transfusion Centre", "Rajshahi", "Rajpara"],
  ["10027217", "IDEAL HEALTH CITY &  BLOOD BANK", "Rangpur", "Rangpur Sadar"],
  ["10028734", "Kasir Uddin Memorial Medical College &  Hospital", "Rangpur", "Rangpur Sadar"],
  ["10022893", "Khwaja Yunus Ali Medical College & Hospital", "Sirajganj", "Chauhali"],
  ["10027655", "NORTH BENGAL MEDICAL COLLEGE HOSPITAL", "Sirajganj", "Sirajganj Sadar"],
  ["10034633", "Sirajgonj Community Hospital  & Blood Bank", "Sirajganj", "Sirajganj Sadar"],
  ["10027511", "Crescent Blood Bank", "Sylhet", "Sylhet Sadar"],
  ["10030699", "Ibn Sina Hospital Sylhet Limited", "Sylhet", "Sylhet Sadar"],
  ["10034395", "Jalalabad Ragib-Rabeya Medical College  Hospital Blood Bank", "Sylhet", "Sylhet Sadar"],
  ["10029549", "North East Medical College Hospital Blood Bank", "Sylhet", "Dakshin Surma"],
  ["10021921", "Parkview Medical College Hospital Blood Bank", "Sylhet", "Sylhet Sadar"],
  ["10035083", "BROTI BLOOD BANK & LAB", "Tangail", "Tangail Sadar"],
  ["10038914", "DHAKA CLINIC & NURSING HOME", "Tangail", "Tangail Sadar"],
  ["10033438", "JAMUNA BLOOD BANK & LAB", "Tangail", "Tangail Sadar"],
  ["10034654", "TANGAIL BLOOD BANK", "Tangail", "Tangail Sadar"],
  ["10038892", "BANDHAN BLOOD BANK O SANCHALAN KENDRO", "Thakurgaon", "Thakurgaon Sadar"],
  ["10038917", "SONDHANI BLOOD BANK & TRANSFUSION CENTER, THAKURGAON", "Thakurgaon", "Thakurgaon Sadar"],
  ["10033461", "THAKURGAON BLOOD BANK AND TRANSFUSION CENTER", "Thakurgaon", "Thakurgaon Sadar"],
] as const;

export const REGISTERED_BLOOD_BANKS: readonly RegisteredCollectionFacility[] =
  REGISTERED_BLOOD_BANK_ROWS.map(([registryCode, name, district, locality]) => ({
    registryCode,
    name,
    district,
    locality,
  }));
