import { FormEvent, useEffect, useState } from 'react';
import { Building2, CalendarDays, MapPin } from 'lucide-react';
import { api } from '../lib/api';
import { BD_LOCATION_NAMES } from '../lib/locations';

export default function PartnersPage({ user }: { user: any }) {
  const [organizations, setOrganizations] = useState<any[]>([]);
  const [form, setForm] = useState({ name: '', type: 'HOSPITAL', district: '', address: '', phone: '', website: '', registration_reference: '' });
  const [message, setMessage] = useState('');
  useEffect(() => { api.getOrganizations().then(setOrganizations).catch(() => setOrganizations([])); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); setMessage(''); try { await api.applyOrganization(form); setMessage('Application submitted for operator verification.'); } catch (error: any) { setMessage(error.message); } };

  return <div className="space-y-8"><header><p className="text-xs uppercase tracking-widest font-bold text-primary">Verified partners</p><h1 className="text-3xl font-extrabold mt-2">Hospitals, blood banks and NGOs</h1><p className="text-slate-500 mt-2">Verification confirms that Drop operations reviewed the submitted organization reference. It is not a clinical endorsement.</p></header>
    <section className="grid gap-4 md:grid-cols-2">{organizations.length === 0 && <p className="text-slate-500">No verified partners are listed yet.</p>}{organizations.map(org => <article key={org.id} className="theme-card border p-6"><div className="flex gap-3 items-center"><Building2 className="text-primary" /><h2 className="font-bold text-xl">{org.name}</h2></div><p className="text-xs font-bold text-emerald-700 mt-2">VERIFIED {org.type.replace('_', ' ')}</p><p className="text-sm text-slate-600 mt-3 flex gap-2"><MapPin className="w-4 h-4" />{org.address}, {org.district}</p><p className="text-sm mt-2">{org.phone}</p>{org.campaigns?.map((campaign: any) => <div key={campaign.id} className="mt-4 p-3 bg-rose-50 rounded-xl"><p className="font-bold text-sm flex gap-2"><CalendarDays className="w-4 h-4" />{campaign.title}</p><p className="text-xs mt-1">{campaign.location} · {new Date(campaign.starts_at).toLocaleDateString()}</p></div>)}</article>)}</section>
    <section className="theme-card border p-6"><h2 className="text-xl font-bold">Apply as an organization</h2>{!user ? <p className="mt-3 text-sm text-slate-500">Log in with a verified account to apply.</p> : <form onSubmit={submit} className="mt-5 grid gap-3 sm:grid-cols-2"><input required placeholder="Legal organization name" value={form.name} onChange={e => setForm({...form, name:e.target.value})} className="input" /><select value={form.type} onChange={e => setForm({...form, type:e.target.value})} className="input"><option value="HOSPITAL">Hospital</option><option value="BLOOD_BANK">Blood bank</option><option value="NGO">NGO</option></select><select required value={form.district} onChange={e => setForm({...form, district:e.target.value})} className="input"><option value="">District</option>{BD_LOCATION_NAMES.map(name => <option key={name}>{name}</option>)}</select><input required placeholder="Official phone" value={form.phone} onChange={e => setForm({...form, phone:e.target.value})} className="input" /><input required placeholder="Full address" value={form.address} onChange={e => setForm({...form, address:e.target.value})} className="input sm:col-span-2" /><input required placeholder="Registration / license reference" value={form.registration_reference} onChange={e => setForm({...form, registration_reference:e.target.value})} className="input" /><input placeholder="Website (optional)" value={form.website} onChange={e => setForm({...form, website:e.target.value})} className="input" />{message && <p role="status" className="text-sm font-bold sm:col-span-2">{message}</p>}<button className="primary-button sm:col-span-2">Submit for verification</button></form>}</section>
  </div>;
}
